### ISSUE TITLE
Ошибка при переводе object has no attribute 'group'

### ISSUE THREAD

**Issue by mihailtugushev** [fantomnotabene/Alfred-GTranslator-workflow#10]
Стала рандомно возникать проблема при переводе. 
<img src="https://d.pr/i/VBDjmR+" alt="text" width="100%" height="100%">
<img src="https://d.pr/i/JQ1oLo+" alt="text" width="100%" height="100%">
Стоит еще 5-10 секунд подождать и перевод возобновляется. Так и не понял откуда это взялось. Но появилась со вчерашнего дня. 

`[22:52:02.290] Logging Started...
[22:52:05.087] Translate[Script Filter] Queuing argument 'а'
[22:52:05.818] Translate[Script Filter] Queuing argument 'ап'
[22:52:05.945] Translate[Script Filter] Queuing argument 'апе'
[22:52:06.049] Translate[Script Filter] Queuing argument 'апел'
[22:52:06.252] Translate[Script Filter] Queuing argument 'апель'
[22:52:06.312] Translate[Script Filter] Queuing argument 'апельс'
[22:52:06.494] Translate[Script Filter] Queuing argument 'апельси'
[22:52:06.663] Translate[Script Filter] Queuing argument 'апельсин'
[22:52:07.499] Translate[Script Filter] Queuing argument 'апельсин '
[22:52:08.636] Translate[Script Filter] Script with argv 'апельсин ' finished
[22:52:08.641] ERROR: Translate[Script Filter] Code 1: .
22:52:07 workflow.py:2061 DEBUG    ---------- Translate (1.3.0) ----------
22:52:07 connectionpool.py:943 DEBUG    Starting new HTTPS connection (1): translate.google.com:443
22:52:08 connectionpool.py:442 DEBUG    https://translate.google.com:443 "GET / HTTP/1.1" 200 None
22:52:08 workflow.py:2080 ERROR    'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/Users/mt/Google Диск/personal/06 software/macos/backup/alfred/Alfred.alfredpreferences/workflows/user.workflow.768E7F36-7521-4B56-80EA-070CF838D222/workflow/workflow.py", line 2073, in run
    func(self)
  File "/Users/mt/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/D0B8B26E-8B43-46C9-9D04-DF6F4A92D4C7", line 14, in main
    result = translator.smart_translate(wf.args[0])
  File "/Users/mt/Google Диск/personal/06 software/macos/backup/alfred/Alfred.alfredpreferences/workflows/user.workflow.768E7F36-7521-4B56-80EA-070CF838D222/translator.py", line 15, in smart_translate
    result = self.translate_text(text)
  File "/Users/mt/Google Диск/personal/06 software/macos/backup/alfred/Alfred.alfredpreferences/workflows/user.workflow.768E7F36-7521-4B56-80EA-070CF838D222/translator.py", line 9, in translate_text
    return self.translate(text, src=src, dest=(dest or self.__dest))
  File "/Users/mt/Google Диск/personal/06 software/macos/backup/alfred/Alfred.alfredpreferences/workflows/user.workflow.768E7F36-7521-4B56-80EA-070CF838D222/googletrans/client.py", line 172, in translate
    data = self._translate(text, dest, src)
  File "/Users/mt/Google Диск/personal/06 software/macos/backup/alfred/Alfred.alfredpreferences/workflows/user.workflow.768E7F36-7521-4B56-80EA-070CF838D222/googletrans/client.py", line 75, in _translate
    token = self.token_acquirer.do(text)
  File "/Users/mt/Google Диск/personal/06 software/macos/backup/alfred/Alfred.alfredpreferences/workflows/user.workflow.768E7F36-7521-4B56-80EA-070CF838D222/googletrans/gtoken.py", line 200, in do
    self._update()
  File "/Users/mt/Google Диск/personal/06 software/macos/backup/alfred/Alfred.alfredpreferences/workflows/user.workflow.768E7F36-7521-4B56-80EA-070CF838D222/googletrans/gtoken.py", line 65, in _update
    code = unicode(self.RE_TKK.search(r.text).group(1)).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'
22:52:08 workflow.py:2103 DEBUG    ---------- finished in 0.952s ----------
[22:52:08.645] Translate[Script Filter] {
  "items": [
    {
      "valid": false,
      "subtitle": "'NoneType' object has no attribute 'group'",
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
      },
      "title": "Error in workflow 'Translate'"
    }
  ]
}
`

При этом другие слова переводятся вполне корректно
<img src="https://d.pr/i/5iA6RW+" alt="text" width="100%" height="100%">
<img src="https://d.pr/i/dC3QwR+" alt="text" width="100%" height="100%">

**Comment by fantomnotabene** [comment]
Похоже, проблема в используемой библиотеке (или в сервисе, под изменения в котором неофициальная библиотека попросту не успевает подстраиваться) 
Есть мысль как это, весьма топорно, обойти
Повторять попытки пока не получим валидный результат и выдавать уже только его
Проверю и выложу фикс если все пройдет гладко

**Comment by fantomnotabene** [comment]
@mihailtugushev, попробуйте [исправленный вариант](https://github.com/fantomnotabene/Alfred-GTranslator-workflow/files/5506611/NotaBene-GTranslator.zip), должно работать

**Comment by misha-tgshv** [comment]
Да, но все работает, но кажется есть задержка в скорости перевода. Не наблюдали? 

И спасибо, что оперативно работаете над исправлениями. Воркфлоу используется каждый день и без него, как без рук :(

**Comment by notabene00** [comment]
Да, всё дело именно в топорности подхода к решению проблемы
Скорее даже не решению, а обходу, ибо глубоко разобраться в причинах падения подкапотной библиотеки я пока даже не пытался
Сейчас я обхожу показ ошибки пользователю простейшим образом: в случае возникновения ошибки, я просто отправляю запрос заново, если снова ошибка - снова заново
На каждый запрос уходит время, отсюда и задержка
Если там всегда будет происходить ошибка, кстати, - уйдет в бесконечный цикл пока не упадет на максимальной глубине рекурсии..
Надо будет как-то иначе эту проблему зачинить, но пока так

**Comment by notabene00** [comment]
А вот и оригинальный ишью в репо подкапотной либы: https://github.com/ssut/py-googletrans/issues/234
